---
title: "Covid-19 - Portugal"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet.extras)
library(magrittr)
library(sqldf)
library(data.table)
library(plyr)
library(dplyr)
library(geoR)
library(sp)
library(xts)
library(dygraphs)
library(sqldf)
library(lubridate)
library(stats)
library(googleVis)
op <- options(gvis.plot.tag='chart')

Confirmed<-readRDS("country_confirmed.rds", refhook = NULL) 
paises<-unique(Confirmed$Country.Region)

selcon<-Confirmed %>%
  dplyr::filter(Country.Region == paises[136]) 
 
library(sqldf)
data_1_occur <- sqldf("select * from selcon where  confirmed_cases > 0 order by Date asc")

total_cres_Confirmed<-data.frame()
tam<-length(data_1_occur$Date)  
for(n in 1:tam) {
     if(tam != n) {
     data_cres<-data_1_occur$confirmed_cases[n+1] - data_1_occur$confirmed_cases[n]
     cres<-data.frame(data_1_occur$Date[n+1],data_1_occur$Date[n],data_1_occur$confirmed_cases[n+1],data_1_occur$confirmed_cases[n],data_cres)
     total_cres_Confirmed<-rbind.fill(cres,total_cres_Confirmed)
     }
}
names(total_cres_Confirmed)<-c("data_actual","d-1","casos_data_actual","casos_d-1","diferenca")
perc<-(total_cres_Confirmed$diferenca*100)/ total_cres_Confirmed$casos_data_actual
total_cres_Confirmed$percentual<-perc
df<-as.data.frame(total_cres_Confirmed)
vsc<-sqldf("select  * from df order by casos_data_actual asc")

 
#
deaths<-readRDS("country_deaths.rds", refhook = NULL) 
paises<-unique(deaths$Country.Region)

seldea<-deaths %>%
  dplyr::filter(Country.Region == paises[50]) 

library(sqldf)
data_1_occur <- sqldf("select * from seldea where  deaths_cases > 0 order by Date asc")

total_cres_deaths<-data.frame()
tam<-length(data_1_occur$Date)  
for(n in 1:tam) {
  if(tam != n) {
    data_cres<-data_1_occur$deaths_cases[n+1] - data_1_occur$deaths_cases[n]
    cres<-data.frame(data_1_occur$Date[n+1],data_1_occur$Date[n],data_1_occur$deaths_cases[n+1],data_1_occur$deaths_cases[n],data_cres)
    total_cres_deaths<-rbind.fill(cres,total_cres_deaths)
  }
}
names(total_cres_deaths)<-c("data_actual","d-1","casos_data_actual","casos_d-1","diferenca")
perc<-(total_cres_deaths$diferenca*100)/ total_cres_deaths$casos_data_actual
total_cres_deaths$percentual<-perc
df<-as.data.frame(total_cres_deaths)
vsd<-sqldf("select  * from df order by casos_data_actual asc")

#
recovered<-readRDS("country_Recovered.rds", refhook = NULL) 
paises<-unique(recovered$Country.Region)

selrec<-recovered %>%
  dplyr::filter(Country.Region == paises[50]) 

library(sqldf)
data_1_occur <- sqldf("select * from selrec where  Recovered_cases > 0 order by Date asc")

total_cres_recovered<-data.frame()
tam<-length(data_1_occur$Date)  
for(n in 1:tam) {
  if(tam != n) {
    data_cres<-data_1_occur$Recovered_cases[n+1] - data_1_occur$Recovered_cases[n]
    cres<-data.frame(data_1_occur$Date[n+1],data_1_occur$Date[n],data_1_occur$Recovered_cases[n+1],data_1_occur$Recovered_cases[n],data_cres)
    total_cres_recovered<-rbind.fill(cres,total_cres_recovered)
  }
}
names(total_cres_recovered)<-c("data_actual","d-1","casos_data_actual","casos_d-1","diferenca")
perc<-(total_cres_recovered$diferenca * 100)/ total_cres_recovered$casos_data_actual
total_cres_recovered$percentual<-perc
df<-as.data.frame(total_cres_recovered)
vsr<-sqldf("select  * from df order by casos_data_actual asc")

 
 
```

Column {data-width=350}
-----------------------------------------------------------------------

### Confirmed

```{r plotg0,  results='asis', tidy=FALSE, echo=FALSE}
t<-paste("COVID-19 - % Confirmed  - " ,"Portugal")
Line1 <- gvisLineChart(vsc, xvar="data_actual", yvar=c("percentual"),
                       options=list(title=t,gvis.editor="Graph",
                       titleTextStyle="{color:'red',fontName:'Courier',fontSize:16}",
                       curveType='function',width=460,height=600))   
plot(Line1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Deaths

```{r plotg1,  results='asis', tidy=FALSE, echo=FALSE}
t<-paste("COVID-19 - % Deaths  - " ,paises[50])
Line1 <- gvisLineChart(vsd, xvar="data_actual", yvar=c("percentual"),
                       options=list(title=t,gvis.editor="Graph",
                       titleTextStyle="{color:'red',fontName:'Courier',fontSize:16}",
                       curveType='function',width=460,height=600))   
plot(Line1)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Recovered

```{r plotg2,  results='asis', tidy=FALSE, echo=FALSE}
t<-paste("COVID-19 - % Recovered  - " ,paises[50])
Line1 <- gvisLineChart(vsr, xvar="data_actual", yvar=c("percentual"),
                       options=list(title=t,gvis.editor="Graph",
                       titleTextStyle="{color:'red',fontName:'Courier',fontSize:16}",
                       curveType='function',width=460,height=600))   
plot(Line1)
```